Update odysseyra1n

diff --git a/scripts/odysseyra1n b/scripts/odysseyra1n
--- a/scripts/odysseyra1n
+++ b/scripts/odysseyra1n
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 # Load functions and variables
 . /usr/bin/common
 cd /root/odysseyra1n/
@@ -6,110 +6,121 @@ cd /root/odysseyra1n/
 # Show ASCII art
 odysseyra1n_logo
 
-echo "odysseyra1n deployment script"
-echo "(C) 2020, CoolStar. All Rights Reserved"
+# * Removed "$(uname)" = "Darwin" condition
+# * Removed CURRENTDIR and ODYSSEYDIR variables
+
+echo "Odysseyra1n Installation Script"
+echo "(C) 2021, CoolStar. All Rights Reserved"
 echo ""
 echo 'This script has been modified to work on odysseyn1x.'
-echo ''
-echo 'First restore rootfs using the ckeckra1n app.'
-echo "Then jailbreak using checkra1n, but don’t open the loader."
+echo "Before you begin: If you're currently jailbroken with a different bootstrap installed, you will need to Reset System via the Loader app before running this script."
+# * Two following lines were added
+echo "Then jailbreak using checkra1n but don't install Cydia."
 echo 'Connect your iDevice to this computer'
-echo ''
-read -p 'Press enter to continue'
+echo "Press enter to continue."
+read -r
 
-iproxy 4444 44 >> /dev/null 2>/dev/null &
+# * Removed check if curl and iproxy are installed
+# * Removed "${ARM}" != yes condition
+# * Removed cd "$ODYSSEYDIR"
+echo '#!/bin/bash' > odysseyra1n-install.bash
+# * Removed "${ARM}" != yes condition
+# * Removed gzip decompression because we are using xz decompressed archives
+cat << "EOF" >> odysseyra1n-install.bash
+if [[ -f "/.bootstrapped" ]]; then
+    echo "Error: Migration from other bootstraps is no longer supported."
+    rm ./bootstrap* ./*.deb odysseyra1n-install.bash
+    exit 1
+fi
+if [[ -f "/.installed_odyssey" ]]; then
+        echo "Error: Odysseyra1n is already installed."
+        rm ./bootstrap* ./*.deb odysseyra1n-install.bash
+        exit 1
+fi
+VER=$(/binpack/usr/bin/plutil -key ProductVersion /System/Library/CoreServices/SystemVersion.plist)
+if [[ "${VER%%.*}" -ge 12 ]] && [[ "${VER%%.*}" -lt 13 ]]; then
+    CFVER=1500
+elif [[ "${VER%%.*}" -ge 13 ]]; then
+    CFVER=1600
+elif [[ "${VER%%.*}" -ge 14 ]]; then
+    CFVER=1700
+else
+    echo "${VER} not compatible."
+    exit 1
+fi
+mount -o rw,union,update /dev/disk0s1s1
+rm -rf /etc/{alternatives,apt,ssl,ssh,dpkg,profile{,.d}} /Library/dpkg /var/{cache,lib}
+tar --preserve-permissions -xkf bootstrap_${CFVER}.tar -C /
+SNAPSHOT=$(snappy -s | cut -d ' ' -f 3 | tr -d '\n')
 
-# Removed ! ${ARM} condition and gzip decompression because we are using xz decompressed archives
-echo '#!/bin/bash' > odyssey-device-deploy.sh
-echo 'cd /var/root' >> odyssey-device-deploy.sh
-echo 'if [[ -f "/.bootstrapped" ]]; then' >> odyssey-device-deploy.sh
-echo 'mkdir -p /odyssey && mv migration /odyssey' >> odyssey-device-deploy.sh
-echo 'chmod 0755 /odyssey/migration' >> odyssey-device-deploy.sh
-echo '/odyssey/migration' >> odyssey-device-deploy.sh
-echo 'rm -rf /odyssey' >> odyssey-device-deploy.sh
-echo 'else' >> odyssey-device-deploy.sh
-echo 'VER=$(/binpack/usr/bin/plutil -key ProductVersion /System/Library/CoreServices/SystemVersion.plist)' >> odyssey-device-deploy.sh
-echo 'if [[ "${VER%%.*}" -ge 12 ]] && [[ "${VER%%.*}" -lt 13 ]]; then' >> odyssey-device-deploy.sh
-echo 'CFVER=1500' >> odyssey-device-deploy.sh
-echo 'elif [[ "${VER%%.*}" -ge 13 ]]; then' >> odyssey-device-deploy.sh
-echo 'CFVER=1600' >> odyssey-device-deploy.sh
-echo 'elif [[ "${VER%%.*}" -ge 14 ]]; then' >> odyssey-device-deploy.sh
-echo 'CFVER=1700' >> odyssey-device-deploy.sh
-echo 'else' >> odyssey-device-deploy.sh
-echo 'echo "${VER} not compatible."' >> odyssey-device-deploy.sh
-echo 'exit 1' >> odyssey-device-deploy.sh
-echo 'fi' >> odyssey-device-deploy.sh
-echo 'mount -uw -o union /dev/disk0s1s1' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/profile' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/profile.d' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/alternatives' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/apt' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/ssl' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/ssh' >> odyssey-device-deploy.sh
-echo 'rm -rf /etc/dpkg' >> odyssey-device-deploy.sh
-echo 'rm -rf /Library/dpkg' >> odyssey-device-deploy.sh
-echo 'rm -rf /var/cache' >> odyssey-device-deploy.sh
-echo 'rm -rf /var/lib' >> odyssey-device-deploy.sh
-echo 'tar --preserve-permissions -xkf bootstrap_${CFVER}.tar -C /' >> odyssey-device-deploy.sh
-printf %s 'SNAPSHOT=$(snappy -s | ' >> odyssey-device-deploy.sh
-printf %s "cut -d ' ' -f 3 | tr -d '\n')" >> odyssey-device-deploy.sh
-echo '' >> odyssey-device-deploy.sh
-echo 'snappy -f / -r $SNAPSHOT -t orig-fs' >> odyssey-device-deploy.sh
-echo 'fi' >> odyssey-device-deploy.sh
-echo '/usr/libexec/firmware' >> odyssey-device-deploy.sh
-echo 'mkdir -p /etc/apt/sources.list.d/' >> odyssey-device-deploy.sh
-echo 'echo "Types: deb" > /etc/apt/sources.list.d/odyssey.sources' >> odyssey-device-deploy.sh
-echo 'echo "URIs: https://repo.theodyssey.dev/" >> /etc/apt/sources.list.d/odyssey.sources' >> odyssey-device-deploy.sh
-echo 'echo "Suites: ./" >> /etc/apt/sources.list.d/odyssey.sources' >> odyssey-device-deploy.sh
-echo 'echo "Components: " >> /etc/apt/sources.list.d/odyssey.sources' >> odyssey-device-deploy.sh
-echo 'echo "" >> /etc/apt/sources.list.d/odyssey.sources' >> odyssey-device-deploy.sh
-echo 'mkdir -p /etc/apt/preferences.d/' >> odyssey-device-deploy.sh
-echo 'echo "Package: *" > /etc/apt/preferences.d/odyssey' >> odyssey-device-deploy.sh
-echo 'echo "Pin: release n=odyssey-ios" >> /etc/apt/preferences.d/odyssey' >> odyssey-device-deploy.sh
-echo 'echo "Pin-Priority: 1001" >> /etc/apt/preferences.d/odyssey' >> odyssey-device-deploy.sh
-echo 'echo "" >> /etc/apt/preferences.d/odyssey' >> odyssey-device-deploy.sh
-echo 'if [[ $VER = 12.1* ]] || [[ $VER = 12.0* ]]; then' >> odyssey-device-deploy.sh
-echo 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games dpkg -i org.swift.libswift_5.0-electra2_iphoneos-arm.deb' >> odyssey-device-deploy.sh
-echo 'fi' >> odyssey-device-deploy.sh
-echo 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games dpkg -i org.coolstar.sileo_2.0.0b6_iphoneos-arm.deb' >> odyssey-device-deploy.sh
-echo 'uicache -p /Applications/Sileo.app' >> odyssey-device-deploy.sh
-echo 'echo -n "" > /var/lib/dpkg/available' >> odyssey-device-deploy.sh
-echo '/Library/dpkg/info/profile.d.postinst' >> odyssey-device-deploy.sh
-echo 'touch /.mount_rw' >> odyssey-device-deploy.sh
-echo 'touch /.installed_odyssey' >> odyssey-device-deploy.sh
-echo 'rm bootstrap*.tar*' >> odyssey-device-deploy.sh
-echo 'rm migration' >> odyssey-device-deploy.sh
-echo 'rm org.coolstar.sileo_2.0.0b6_iphoneos-arm.deb' >> odyssey-device-deploy.sh
-echo 'rm org.swift.libswift_5.0-electra2_iphoneos-arm.deb' >> odyssey-device-deploy.sh
-echo 'rm odyssey-device-deploy.sh' >> odyssey-device-deploy.sh
+snappy -f / -r "$SNAPSHOT" -t orig-fs > /dev/null 2>&1
+/prep_bootstrap.sh >/dev/null 2>&1
+PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games
+if [[ $VER = 12.1* ]] || [[ $VER = 12.0* ]]; then
+    dpkg -i org.swift.libswift_5.0-electra2_iphoneos-arm.deb > /dev/null
+fi
+echo "(4) Installing Sileo..."
+dpkg -i org.coolstar.sileo_2.0.3_iphoneos-arm.deb > /dev/null
+mkdir -p /etc/apt/sources.list.d /etc/apt/preferences.d
+{
+    echo "Types: deb"
+    echo "URIs: https://repo.theodyssey.dev/"
+    echo "Suites: ./"
+    echo "Components: "
+    echo ""   
+} > /etc/apt/sources.list.d/odyssey.sources
+touch /var/lib/dpkg/available
+touch /.mount_rw
+touch /.installed_odyssey
+rm ./bootstrap* ./*.deb odysseyra1n-install.bash
+echo "Done!"
+EOF
 
+# * Following line was added
 clear
 
+# * Added xz decompression
 if ! ls ./*.tar > /dev/null 2>&1; then
-	whatstep 'Extracting files'
+	blue_echo 'Extracting resources...'
 	if xz -vd ./*.tar.xz; then
-		successful 'extracting files'
+		green_echo 'Done extracting resources.'
 	else
-		failed 'extract files'
+		failed 'Failed to extract resources.'
 	fi
 fi
 
-whatstep 'Copying files to your device'
-# Removed .gz extension because where are using xz decrompressed archives
-if sshpass -p 'alpine' scp -P4444 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" bootstrap_1500.tar bootstrap_1600.tar bootstrap_1700.tar migration org.coolstar.sileo_2.0.0b6_iphoneos-arm.deb org.swift.libswift_5.0-electra2_iphoneos-arm.deb odyssey-device-deploy.sh root@127.0.0.1:/var/root/; then
-	successful 'copying files to your device'
-else
-	failed 'copy files to your device'
-fi
+# * Removed resource downloads
+IPROXY=$(iproxy 28605 44 >/dev/null 2>&1 & echo $!)
 
-whatstep 'Installing Procursus bootstrap and Sileo on your device'
-if sshpass -p 'alpine' ssh -p4444 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" root@127.0.0.1 "bash /var/root/odyssey-device-deploy.sh"; then
-	successful 'installing Procursus bootstrap and Sileo on your device'
-	killall iproxy
-	echo 'Open Sileo, do all the updates and install the libhooker package.'
-	echo 'Then re-jailbreak your device.'
-	echo -e "${BOLD}Change the mobile/root passwords to prevent the possibility of unsavory people remotely logging into your device throught SSH using the default password.${NORMAL}"
-	read -p 'Press enter to quit'
+# * Removed ! "${ARM}" = yes condition
+# * echo with blue instead of white
+blue_echo "Copying resources to your device..."
+# * Removed password indication
+# * Added check if command is successful
+# * Added sshpass -p 'alpine'
+# * Removed .gz extension because where are using xz decrompressed archives
+if sshpass -p 'alpine' scp -qP28605 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" bootstrap_1500.tar.gz \
+	bootstrap_1600.tar bootstrap_1700.tar \
+	org.coolstar.sileo_2.0.3_iphoneos-arm.deb \
+	org.swift.libswift_5.0-electra2_iphoneos-arm.deb \
+	odysseyra1n-install.bash \
+	root@127.0.0.1:/var/root/; then
+	green_echo 'Done copying resources to your device.'
 else
-	failed 'install Procursus bootstrap and Sileo on your device'
+	red_echo 'Failed to copy resources to your device.'
 fi
+# * echo with blue instead of white
+blue_echo "Bootstrapping your device..."
+# * Removed "${ARM}" = yes condition
+# * Removed password indication
+# * Added check if command is successful
+# * Added sshpass -p 'alpine'
+if sshpass -p 'alpine' ssh -qp28605 -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" root@127.0.0.1 "bash /var/root/odysseyra1n-install.bash"; then
+	green_echo 'Done bootstrapping your device.'
+else
+	red_echo 'Failed to bootstrap your device.'
+fi
+# * Removed cd "$CURRENTDIR" and rm -rf "$ODYSSEYDIR"
+kill "$IPROXY"
+echo "${BOLD}Change the mobile/root passwords to prevent the possibility of unsavory people remotely logging into your device through SSH using the default password.${NORMAL}"
+enter_to_quit
